name: my_calendar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Favourite library
  share: ^2.0.1
  provider: ^6.0.4
  device_info: ^2.0.0
  flutter_bloc: ^8.1.1
  package_info: ^2.0.0
  connectivity_plus: ^3.0.2
  url_launcher: ^6.0.5
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  lint: ^1.6.0
  image_picker: 0.8.6
  file_picker: ^5.2.2
  keyboard_dismisser: ^3.0.0

  #Library helpful
  intl: ^0.17.0
  event_bus: ^2.0.0
  equatable: ^2.0.0
  fluttertoast: ^8.0.3
  retrofit: ^2.0.1
  json_annotation: ^4.0.1
  cached_network_image: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  logger: any
  rxdart: ^0.27.1
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  path: ^1.8.2
  # GETX
  get: ^4.1.4
  pretty_dio_logger: ^1.1.1
  injectable: ^1.4.1
  freezed: ^0.14.2

  # firebase
  firebase_messaging: ^14.0.2
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0

  #XKLD
  dots_indicator: ^2.0.0
  flutter_svg: ^1.0.3
  cool_dropdown: ^1.4.1
  pin_code_fields: ^7.3.0
  image_res: ^0.3.0  #flutter packages pub run image_res:main watch
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0+3
  pull_to_refresh: ^2.0.0
  list_tile_switch: ^1.0.0
  flutter_switch: ^0.3.2
  loading_gifs: ^0.3.0
  expandable_page_view: ^1.0.10
  youtube_player_iframe: ^3.1.0
  youtube_player_flutter: ^8.0.0
  image_cropper: ^3.0.1
  video_player: ^2.2.17
  chewie: ^1.2.2
  flutter_speed_dial: ^6.2.0
  local_auth: ^2.1.2
  queue: ^3.1.0+1
  flutter_staggered_grid_view: ^0.6.1
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1
  simple_speed_dial: ^0.1.3
  syncfusion_flutter_pdfviewer: ^20.3.57
  scrollable_positioned_list: ^0.3.5
  sticky_headers: ^0.3.0+2
  numerus: ^2.0.0
  flutter_layout_grid: ^2.0.1
  flutter_rounded_date_picker: ^3.0.2
  google_fonts: ^3.0.1
  simple_gesture_detector: ^0.2.0
  lunar_calendar_converter_new: ^2.0.0
  collection: ^1.16.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  google_sign_in: ^5.4.2
  swipe_to: ^1.0.2
  http: ^0.13.5
  oauth2: ^2.0.1
  #webview_flutter: ^3.0.4
  tibetan_calendar: ^0.0.4
  hive: ^2.2.3
  analyzer: any
  flutter_slidable: ^2.0.0
  firebase_database: ^10.0.15
  html: ^0.15.3
#  scroll_to_index: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  hive_generator:
  build_runner: 2.1.1  #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.0
  injectable_generator: ^1.4.1
  flutter_lints: ^1.0.0
  lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true